### ISSUE TITLE
double publishing only over MQTT

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/driver-bacnet#104]
It seems driver bacnet is sending the same request twice every time

![image](https://github.com/NubeIO/driver-bacnet/assets/18637436/91ba4883-05e8-478f-9bfa-d9878d3a9d9f)

![image](https://github.com/NubeIO/driver-bacnet/assets/18637436/c814a421-369c-4654-9a00-9b3b4c4aace0)

**Comment by shomaglasang** [comment]
Hi mate @NubeDev checking this one.

**Comment by shomaglasang** [comment]
Hi @NubeDev I can't seem to replicate this on my devel environment and in the office device at 192.168.15.17. From your screenshot, It looks like the driver bacnet received the same (duplicate) MQTT message twice. Am I correct? The topic of the duplicate messages from your screenshot is "bacnet/cmd/write_value". These messages (topic) are not published by the driver bacnet but by a client over MQTT.

**Comment by shomaglasang** [comment]
Hi mate @NubeDev The fix is included in 1.0.2-rc.3 https://github.com/NubeIO/driver-bacnet/releases/tag/v1.0.2-rc.3
Please try this latest version. Initial testing on the office device is good. I will merge the PR if I don't find any issue. Thanks

**Comment by shomaglasang** [comment]
Mate @NubeDev Closing this issue.
