### ISSUE TITLE
Discover device data discrepancy over the time

### ISSUE THREAD

**Issue by RaiBnod** [NubeIO/driver-bacnet#122]
Version of `driver-bacnet`: `v1.0.0-rc.5`

When we are having this issue https://github.com/NubeIO/driver-bacnet/issues/121, the device gets discovered **(but names don't look good)** but points don't (`0 points`).

### When it's having that issue:

![image](https://github.com/NubeIO/driver-bacnet/assets/6800775/54dce249-3182-47ff-8fe9-6c87b9e90e0d)

### After `driver-bacnet` restart:

![image](https://github.com/NubeIO/driver-bacnet/assets/6800775/46d5dc28-ace5-478e-94dc-166f8be54907)

**Comment by RaiBnod** [comment]
It falls on the same issue: https://github.com/NubeIO/driver-bacnet/issues/121

The `whois` command is working fine, names are not being returned. So, it's just adding `deviceID_` in the prefix. So, I expect it should work if we make this https://github.com/NubeIO/driver-bacnet/issues/121 work.

**Comment by shomaglasang** [comment]
@RaiBnod @NubeDev 
This should be resolved by the fix for [#121](https://github.com/NubeIO/driver-bacnet/issues/121)
