### ISSUE TITLE
Support Multi State Points

### ISSUE THREAD

**Issue by CanuckMarc** [NubeIO/driver-bacnet#127]
@shomaglasang  Please use this issue for tracking the BACnet multi state point support.  This is a HIGH priority taks. 

Previous correspondance is on this other issue: https://github.com/NubeIO/driver-bacnet/issues/125

Could you please provide daily updates on your progress and also advise an ETA for the completion of this functionality (including testing).

**Comment by shomaglasang** [comment]
ETA for 1.0.2-rc.2 is july 19th

**Comment by shomaglasang** [comment]
@CanuckMarc @RaiBnod fix included in 1.0.2-rc.2. Test on office device 192.168.15.17.

**Comment by shomaglasang** [comment]
Hi @CanuckMarc will close this issue. The fix is included in 1.0.2-rc.2. I did test it on the office device at 192.168.15.17 and seems to be working fine. Thanks

**Comment by CanuckMarc** [comment]
I have reviewed this update and it looks to be working as intended.  Thanks @shomaglasang

**Comment by shomaglasang** [comment]
Thanks for your feedback @CanuckMarc
