### ISSUE TITLE
High memory usage over the time

### ISSUE THREAD

**Issue by RaiBnod** [NubeIO/driver-bacnet#43]
It starts with low memory usage, but over the time the memory usage by `driver-bacnet` becomes high. See this video:

https://user-images.githubusercontent.com/6800775/221141343-c2ec0461-128b-4c51-b11c-5b27aeb31135.mov

**Comment by RaiBnod** [comment]
More info: it grows memory usage linearly like every 0.1% in 1 minute RC device.

# Time: 3:13 PM NPT
![image](https://user-images.githubusercontent.com/6800775/221144593-b9711cb8-6133-4e4b-a891-5e8e778f7baa.png)

# Time: 3:15 NPT
![image](https://user-images.githubusercontent.com/6800775/221144788-894a76cb-49ad-48c9-be90-610eb1eecbee.png)

# Time: 3:18 NPT
![image](https://user-images.githubusercontent.com/6800775/221144934-92491fa1-318e-4cf3-be84-c6359ab31f43.png)

# Time: 3:19 NPT
![image](https://user-images.githubusercontent.com/6800775/221145010-ac1a276a-2770-4dcd-94dd-e35eb645d460.png)

# Time: 3:20 NPT
![image](https://user-images.githubusercontent.com/6800775/221145091-5cef58a0-ba0c-4904-b798-e0fc04c36a77.png)

**Comment by shomaglasang** [comment]
Thanks @RaiBnod , possible memory leak.
btw, is it receiving a lot of messages?

**Comment by NubeDev** [comment]
yes it is, would be 100 messages evey 5 sec

**Comment by shomaglasang** [comment]
thanks

**Comment by shomaglasang** [comment]
@NubeDev @RaiBnod I created a new release 0.0.32. Found the memory leak in the json parser. Tested the new version on my env and seemed to have fixed the issue. Pls try it out if you can. thanks

**Comment by RaiBnod** [comment]
Working fine as expected.
