### ISSUE TITLE
on bacnet server add MQTT persistence 

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/driver-bacnet#93]
for the bacnet server on boot/restart of the server can you make it get the MQTT last value from persistence 

add it as an option in the config file

make it use persistence by default

```
disablePersistence=true 
```

**Comment by shomaglasang** [comment]
hey mate @NubeDev , just need confirmation on this. The last value is the last value of the topic? Not the last value of the object property (e.g. AI present value)?

**Comment by shomaglasang** [comment]
@NubeDev fyi, included in v0.0.65.
Feature is enabled by default. TO disable it, add the following knob in the config.
```
mqtt:
  disable_persistence: true
```

**Comment by Shiny380** [comment]
#94 #96
